title: My Portfolio
description: Welcome to my personal portfolio!
theme: jekyll-theme-minimal
url: "https://paulina-mile.github.io"
baseurl: ""
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
