title: Paulina Milewska
description: Assistant Eductaional Technologist at University of Hertfordshire
theme: jekyll-theme-slate
url: "https://paulina-mile.github.io"
baseurl: ""
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
